### ISSUE TITLE
Add a diff tool for comparing multiple `Cirq.Circuit`s in Jupyter Notebooks

### ISSUE THREAD

**Issue by freyam** [quantumlib/Cirq#4510]
**Is your feature request related to a use case or problem? Please describe.**

Tanuj has an amazing idea to visualize the differences between circuits. 

**Logger Design**
- `register_initial` and `register_final` methods will be used to maintain the state of the circuits and compute the difference between initial and final circuits. 
- The difference between initial and final circuits will be stored for each call. Also, common stats like circuit depth, number of one / two qubit gates, circuit duration etc. will be computed and stored for each time step. 
- Finally, a plot method will bring up an interactive widget to plot the state of the initial and final circuits highlighting the difference for each time step of the optimization. 

![logger](https://user-images.githubusercontent.com/62539811/133992386-1d0f690e-f7ca-4147-91e8-d4c472018592.gif)

Source: [RFC: Circuit Transformers API #Logger Design](https://docs.google.com/document/d/1f5cizZ_z-bv6XPkJLzHi3H-E_VvPsFykQ9oBAKjf1xM/edit#heading=h.rrkaeq49os6m)

We could adopt this same technique to also implement a new module that shows the difference between N given circuits (N >= 2) in a clean SVG format or a GIF transition. We could adopt to use 3rd party open-source tools for this or a simple SVG diff-tool also might suffice.

**Describe the solution you'd like**

**Task 0**

- [ ] Merge https://github.com/quantumlib/Cirq/issues/4499 which enables us to visualize `cirq.Circuit` in SVG format.

**Task 1**
- [ ] Create a diff tool that takes 2 `cirq.Circuit`s as input and prints the differences between them in a nice way (will share demos soon.)

**Task 2**
- [ ] Upgrade the tool made in Task 1 that takes N `cirq.Circuit`s as input and prints the differences in a neat tabular form or a slider form.

**Task 3**
- [ ] Convert the tool into an IPython widget which can be directly installed in Jupyter Notebooks.

Completing all the 3 tasks would be really helpful to all the users as it would allow an easy way to work around optimizers (and transformers) that modify the circuits. Now, users would be able to track the optimization (or transformation).

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P2 - we should do it in the next couple of quarters 

cc @tanujkhattar

**Comment by tanujkhattar** [comment]
Thank you @freyam for opening this. 

For reference, The [Transformer API RFC](https://tinyurl.com/cirq-circuit-transformers-api) is still under review but I don't expect the logging feature request to change. 

However, There are some design questions that would need to be addressed, for example -- I'm not sure if the Task 2 mentioned above is necessary. Once we have a tool which can plot the diff of two circuits, we could simply use it from the transformer logger to plot all the `N` steps as needed. 

I would suggest to use this issue to track one particular change, i.e. Task 1 mentioned above. It's a clear independent function / tool which can then be used in the larger context of improving visualizations for transformers. 

Once the transformer design is finalized, we can create other issues to track the relevant features (like Task 2 and 3 mentioned above)

**Comment by freyam** [comment]
> I would suggest to use this issue to track one particular change, i.e. Task 1 mentioned above. It's a clear independent function / tool which can then be used in the larger context of improving visualizations for transformers.

> Once the transformer design is finalized, we can create other issues to track the relevant features (like Task 2 and 3 mentioned above)

Works :heavy_check_mark:

**Comment by mhucka** [comment]
I'm closing this as a nice-to-have-but-we-don't-have-time feature request. If this is incorrect or something changes, someone please feel free to reopen it.
