### ISSUE TITLE
Remove public fields from gates

### ISSUE THREAD

**Issue by daxfohl** [quantumlib/Cirq#4851]
We still have a number of gates and operations that have public fields. These should be private, with public getters if necessary. (And those getters should not return mutable references unless it's something performance critical.) Otherwise this breaks the contracts of FrozenCircuit etc. 

Ideally upon fixing this we should create a unit test that checks this to some extent for all gates in Cirq.

This should probably be done before 1.0.

- [x] controlled_gate.py #5061
- [x] controlled_operation.py #5061
- [x] dense_pauli_string.py #5064
- [x] fourier_transform.py #5074
- [x] fsim_gate.py #5075
- [x] measurement_gate.py #5061 
- [x] pauli_interaction_gate.py #5062 
- [x] pauli_measurement_gate.py #5062 
- [x] pauli_string_raw_types.py #5062 
- [x] permutation_gate.py #5074
- [x] random_gate_channel.py #5074
- [x] raw_types.py #5074
- [x] wait_gate.py #5074
```
(cirq-py3) dax@DESKTOP-Q5MLJ3J:~/cirq$ grep -r "self\.[^_][^\ ]*\s=\s" --exclude "*test.py" cirq-core/cirq/ops/*
Binary file cirq-core/cirq/ops/__pycache__/arithmetic_operation.cpython-38.pyc matches
Binary file cirq-core/cirq/ops/__pycache__/arithmetic_operation.cpython-39.pyc matches
cirq-core/cirq/ops/controlled_gate.py:        self.control_qid_shape = tuple(control_qid_shape)
cirq-core/cirq/ops/controlled_gate.py:        self.control_values = cast(
cirq-core/cirq/ops/controlled_gate.py:            self.sub_gate = sub_gate.sub_gate  # type: ignore
cirq-core/cirq/ops/controlled_gate.py:            self.sub_gate = sub_gate
cirq-core/cirq/ops/controlled_operation.py:        self.control_values = cast(
cirq-core/cirq/ops/controlled_operation.py:            self.controls = tuple(controls)
cirq-core/cirq/ops/controlled_operation.py:            self.sub_operation = sub_operation
cirq-core/cirq/ops/controlled_operation.py:            self.controls = tuple(controls) + sub_operation.controls
cirq-core/cirq/ops/controlled_operation.py:            self.sub_operation = sub_operation.sub_operation
cirq-core/cirq/ops/dense_pauli_string.py:        self.pauli_mask = _as_pauli_mask(pauli_mask)
cirq-core/cirq/ops/dense_pauli_string.py:        self.coefficient = (
cirq-core/cirq/ops/dense_pauli_string.py:            self.pauli_mask = np.copy(self.pauli_mask)
cirq-core/cirq/ops/dense_pauli_string.py:            self.pauli_mask[key] = _pauli_index(value)
cirq-core/cirq/ops/dense_pauli_string.py:                self.pauli_mask[key] = value.pauli_mask
cirq-core/cirq/ops/dense_pauli_string.py:                self.pauli_mask[key] = _as_pauli_mask(value)
cirq-core/cirq/ops/dense_pauli_string.py:            self.coefficient = new_coef if isinstance(new_coef, sympy.Basic) else complex(new_coef)
cirq-core/cirq/ops/fourier_transform.py:        self.exponent = exponent
cirq-core/cirq/ops/fsim_gate.py:        self.theta = _canonicalize(theta)
cirq-core/cirq/ops/fsim_gate.py:        self.phi = _canonicalize(phi)
cirq-core/cirq/ops/fsim_gate.py:        self.theta = _canonicalize(theta)
cirq-core/cirq/ops/fsim_gate.py:        self.zeta = _canonicalize(zeta)
cirq-core/cirq/ops/fsim_gate.py:        self.chi = _canonicalize(chi)
cirq-core/cirq/ops/fsim_gate.py:        self.gamma = _canonicalize(gamma)
cirq-core/cirq/ops/fsim_gate.py:        self.phi = _canonicalize(phi)
cirq-core/cirq/ops/measurement_gate.py:        self.key = key  # type: ignore
cirq-core/cirq/ops/measurement_gate.py:        self.invert_mask = invert_mask or ()
cirq-core/cirq/ops/measurement_gate.py:            self.mkey = key
cirq-core/cirq/ops/measurement_gate.py:            self.mkey = value.MeasurementKey(name=key)
cirq-core/cirq/ops/pauli_interaction_gate.py:        self.pauli0 = pauli0
cirq-core/cirq/ops/pauli_interaction_gate.py:        self.invert0 = invert0
cirq-core/cirq/ops/pauli_interaction_gate.py:        self.pauli1 = pauli1
cirq-core/cirq/ops/pauli_interaction_gate.py:        self.invert1 = invert1
cirq-core/cirq/ops/pauli_measurement_gate.py:        self.key = key  # type: ignore
cirq-core/cirq/ops/pauli_measurement_gate.py:        self.mkey = key
cirq-core/cirq/ops/pauli_string_raw_types.py:        self.pauli_string = pauli_string
cirq-core/cirq/ops/permutation_gate.py:        self.permutation = tuple(permutation)
cirq-core/cirq/ops/random_gate_channel.py:        self.sub_gate = sub_gate
cirq-core/cirq/ops/random_gate_channel.py:        self.probability = probability
cirq-core/cirq/ops/random_gate_channel.py:            self.sub_gate = self.sub_gate.sub_gate
cirq-core/cirq/ops/raw_types.py:        self.sub_operation = sub_operation
cirq-core/cirq/ops/wait_gate.py:        self.duration = value.Duration(duration)
```

**Comment by tanujkhattar** [comment]
From cirq sync: 

We should do it. Let's do a deprecation by creating a setter and mark it deprecated.

**Comment by daxfohl** [comment]
@tanujkhattar @MichaelBroughton Do we have anybody that's a linter expert on the team? Seems like a linter that scans the package for all classes directly/indirectly inheriting Gate and checks field names against a regex should be reasonably straightforward to make (like I could do this in maybe 5 lines in C# if this were a .net app). But linter tutorials I see all deal directly with the AST, which seems lower level than what would be ideal. Is there an easy way in Python to get all the classes in a package and inspect their inheritance and field names?
